# Generated by Django 4.1.3 on 2022-12-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("category", models.IntegerField(default=0)),
                ("price", models.PositiveBigIntegerField(default=0)),
                ("name", models.CharField(default="", max_length=30)),
                ("description", models.TextField(default="")),
                ("sales_count", models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
